init:
	mkdir -p {{justfile_directory()}}/mui/common_resources
	cp {{justfile_directory()}}/../common/* {{justfile_directory()}}/mui/common_resources/
	test -d venv || python3 -m venv venv
	. venv/bin/activate; pip3 install -r requirements-dev.txt -r binjastub/requirements.txt

format:
	black .
	isort .

lint:
	black --check .
	isort --check-only .
	mypy

test:
	pytest
