init:
  test -d venv || python3 -m venv venv
  . venv/bin/activate; pip install -U pip setuptools wheel; pip install -e ./manticore/server[dev]

format:
  just --justfile ./manticore/server/justfile -d ./manticore/server format

lint:
  just --justfile ./manticore/server/justfile -d ./manticore/server lint

generate:
  just --justfile ./manticore/server/justfile -d ./manticore/server generate

build:
  just --justfile ./manticore/server/justfile -d ./manticore/server build

install: build
  cp ./manticore/server/dist/* ../plugins/ghidra/MUI/os/linux_x86_64/

test:
  just --justfile ./manticore/server/justfile -d ./manticore/server test
