from typing import Final

BINJA_SETTINGS_GROUP: Final[str] = "mui"
BINJA_NATIVE_RUN_SETTINGS_PREFIX: Final[str] = f"{BINJA_SETTINGS_GROUP}.native_run."
BINJA_HOOK_SETTINGS_PREFIX: Final[str] = f"{BINJA_SETTINGS_GROUP}.hook."
BINJA_EVM_RUN_SETTINGS_PREFIX: Final[str] = f"{BINJA_SETTINGS_GROUP}.evm_run."
